/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientAiScannerRouteImport } from './routes/patient.ai-scanner'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorReportsRouteImport } from './routes/doctor.reports'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor.notifications'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor.availability'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiMonitoringRouteImport } from './routes/admin.ai-monitoring'
import { Route as PatientConsultAppointmentIdRouteImport } from './routes/patient.consult.$appointmentId'
import { Route as DoctorConsultAppointmentIdRouteImport } from './routes/doctor.consult.$appointmentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/patient/settings',
  path: '/patient/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/patient/reports',
  path: '/patient/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/patient/prescriptions',
  path: '/patient/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/patient/notifications',
  path: '/patient/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/patient/doctors',
  path: '/patient/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAiScannerRoute = PatientAiScannerRouteImport.update({
  id: '/patient/ai-scanner',
  path: '/patient/ai-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/doctor/settings',
  path: '/doctor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/doctor/reports',
  path: '/doctor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/doctor/prescriptions',
  path: '/doctor/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/doctor/notifications',
  path: '/doctor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/doctor/availability',
  path: '/doctor/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/doctor/analytics',
  path: '/doctor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiMonitoringRoute = AdminAiMonitoringRouteImport.update({
  id: '/admin/ai-monitoring',
  path: '/admin/ai-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsultAppointmentIdRoute =
  PatientConsultAppointmentIdRouteImport.update({
    id: '/patient/consult/$appointmentId',
    path: '/patient/consult/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoctorConsultAppointmentIdRoute =
  DoctorConsultAppointmentIdRouteImport.update({
    id: '/doctor/consult/$appointmentId',
    path: '/doctor/consult/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai-monitoring': typeof AdminAiMonitoringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/ai-scanner': typeof PatientAiScannerRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/consult/$appointmentId': typeof DoctorConsultAppointmentIdRoute
  '/patient/consult/$appointmentId': typeof PatientConsultAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai-monitoring': typeof AdminAiMonitoringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/ai-scanner': typeof PatientAiScannerRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/doctor/consult/$appointmentId': typeof DoctorConsultAppointmentIdRoute
  '/patient/consult/$appointmentId': typeof PatientConsultAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai-monitoring': typeof AdminAiMonitoringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/ai-scanner': typeof PatientAiScannerRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/consult/$appointmentId': typeof DoctorConsultAppointmentIdRoute
  '/patient/consult/$appointmentId': typeof PatientConsultAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/admin/ai-monitoring'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/availability'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/patient/ai-scanner'
    | '/patient/appointments'
    | '/patient/doctors'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/reports'
    | '/patient/settings'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/doctor/consult/$appointmentId'
    | '/patient/consult/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/admin/ai-monitoring'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/availability'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/patient/ai-scanner'
    | '/patient/appointments'
    | '/patient/doctors'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/reports'
    | '/patient/settings'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/doctor/consult/$appointmentId'
    | '/patient/consult/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/admin/ai-monitoring'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/availability'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/patient/ai-scanner'
    | '/patient/appointments'
    | '/patient/doctors'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/reports'
    | '/patient/settings'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/doctor/consult/$appointmentId'
    | '/patient/consult/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAiMonitoringRoute: typeof AdminAiMonitoringRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  PatientAiScannerRoute: typeof PatientAiScannerRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientDoctorsRoute: typeof PatientDoctorsRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  DoctorConsultAppointmentIdRoute: typeof DoctorConsultAppointmentIdRoute
  PatientConsultAppointmentIdRoute: typeof PatientConsultAppointmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/patient/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/patient/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/patient/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/patient/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/patient/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/ai-scanner': {
      id: '/patient/ai-scanner'
      path: '/patient/ai-scanner'
      fullPath: '/patient/ai-scanner'
      preLoaderRoute: typeof PatientAiScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/doctor/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/doctor/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/doctor/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/doctor/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/doctor/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-monitoring': {
      id: '/admin/ai-monitoring'
      path: '/admin/ai-monitoring'
      fullPath: '/admin/ai-monitoring'
      preLoaderRoute: typeof AdminAiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consult/$appointmentId': {
      id: '/patient/consult/$appointmentId'
      path: '/patient/consult/$appointmentId'
      fullPath: '/patient/consult/$appointmentId'
      preLoaderRoute: typeof PatientConsultAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consult/$appointmentId': {
      id: '/doctor/consult/$appointmentId'
      path: '/doctor/consult/$appointmentId'
      fullPath: '/doctor/consult/$appointmentId'
      preLoaderRoute: typeof DoctorConsultAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAiMonitoringRoute: AdminAiMonitoringRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  PatientAiScannerRoute: PatientAiScannerRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientDoctorsRoute: PatientDoctorsRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  DoctorConsultAppointmentIdRoute: DoctorConsultAppointmentIdRoute,
  PatientConsultAppointmentIdRoute: PatientConsultAppointmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
